shortbus/field/urls.py
from django.conf.urls import *

from shortbus.field import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
)

shortbus/home/urls.py
from django.conf.urls import *

from shortbus.home import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^/about/$', views.about, name='about'),
)

shortbus/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

from djangobb_forum import settings as forum_settings
from sitemap import SitemapForum, SitemapTopic

from shortbus.home import views

admin.autodiscover()

sitemaps = {
    'forum': SitemapForum,
    'topic': SitemapTopic,
}

urlpatterns = patterns('',
    # Landing page
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    
    # Shortbus Field
    (r'^field/$', include('shortbus.field.urls', namespace='field')),

    # Admin
    (r'^admin/', include(admin.site.urls)),

    # Sitemap
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),

    # Apps
    (r'^accounts/', include('allauth.urls')),
    (r'^forum/', include('djangobb_forum.urls', namespace='djangobb')),
    
)

# PM Extension
if (forum_settings.PM_SUPPORT):
    urlpatterns += patterns('',
        (r'^forum/pm/', include('django_messages.urls')),
   )
    
if (settings.DEBUG):
    urlpatterns += patterns('',
        (r'^%s(?P<path>.*)$' % settings.MEDIA_URL.lstrip('/'),
            'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

shortbus/field/models.py
from django.db import models

# Create your models here.

shortbus/home/models.py
from django.db import models

# Create your models here.

shortbus/forms.py
import re
from registration.forms import RegistrationFormUniqueEmail


class RegistrationFormUtfUsername(RegistrationFormUniqueEmail):
    '''
    Allowed UTF8 logins with space
    '''
    def __init__(self, *args, **kwargs):
        super(RegistrationFormUtfUsername, self).__init__(*args, **kwargs)
        self.fields['username'].regex = re.compile(r"^[\w\s-]+$", re.UNICODE)

shortbus/field/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
        return render(request, 'field/index.html')

shortbus/home/views.py
from django.http import HttpResponse
from django.shortcuts import render

def index(request):
    return render(request, 'home/index.html')
    
def about(request):
    return render(request, 'home/about.html')

shortbus/templates/django_messages/base_pm.html
{% extends 'djangobb_forum/base.html' %}
{% load forum_extras %}
{% load i18n %}

{% block content %}
<div class="block2col">
	{% include 'django_messages/menu_pm.html' %}
	
	{% block sub_content %}
	{% endblock %}
	
<div class="clearer"></div>
</div>
{% endblock %}

{% block controls %}
{% endblock %}

shortbus/templates/django_messages/compose.html
{% extends 'django_messages/base_pm.html' %}
{% load forum_extras %}
{% load i18n %}

{% block sub_content %}


<div class="blockform">
	<h2><span>{% trans "Send a message" %}</span></h2>
	<div class="box">


	<form action="" method="post">
		{% csrf_token %}
		<div class="inform">
		<fieldset>
			<legend>{% trans "Write your message and submit" %}</legend>

			<div class="infldset txtarea">
				{{ form.recipient.errors }}
				<label ><strong>{{ form.recipient.label }}</strong><br />{{ form.recipient }}<br /></label>
				{{ form.subject.errors }}
				<label><strong>{{ form.subject.label }}</strong><br />{{ form.subject }}<br /></label>
				{{ form.body.errors }}
				<label><strong>{{ form.body.label }}</strong><br />
				{{ form.body.errors }}
				{{ form.body }}<br /></label>
			</div>
		</fieldset>
			</div>
			<p><input type="submit" name="submit" value="{% trans "Send" %}" tabindex="6" accesskey="s" /><a href="javascript:history.go(-1)">{% trans "Go back" %}</a></p>

		</form>
	</div>
</div>

{% endblock %}

shortbus/templates/django_messages/inbox.html
{% extends 'django_messages/base_pm.html' %}
{% load forum_extras %}
{% load i18n %}
{% block sub_content %}
 <div class="blockform">
	<h2><span>{% trans "Inbox" %}</span></h2>
	<div class="box">
		<div class="inbox">
			<table cellspacing="0">
			<thead>
				<tr>
					<th class="tcl">{% trans "Subject" %}</th>
					<th>{% trans "Sender" %}</th>
					<th class="tcr">{% trans "Date" %}</th>
				</tr>
			</thead>
			<tbody>
			{% if message_list %}
				{% for msg in message_list %}
				<tr {% if msg.new %}class="inew"{% endif %}>
					<td class="tcl">
						<div class="intd">
							<div class="icon"><div class="nosize"><!-- --></div></div>
							<div class="tclcon">
								{% if msg.new %}
									<strong><a href="{% url 'messages_detail' msg.id %}">{{ msg.subject }}</a></strong>
								{% else %}
									<a href="{% url 'messages_detail' msg.id %}">{{ msg.subject }}</a>
								{% endif %}
							</div>
						</div>
					</td>
					<td class="tc2" style="white-space: nowrap; OVERFLOW: hidden"><a href="{% url 'djangobb:forum_profile' msg.sender.username %}">{{ msg.sender.username }}</a></td>
					<td class="tcr" style="white-space: nowrap">{% forum_time msg.sent_at %}</td>
				</tr>
				{% endfor %}
			{% else %}
				<tr><td class="djangobbcon1" colspan="3">{% trans "No messages" %}</td></tr>
			{% endif %}
			</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}

shortbus/templates/django_messages/menu_pm.html
{% load i18n %}
	<div class="blockmenu">
		<h2><span>{% trans "Private Messages" %}</span></h2>
		<div class="box">
			<div class="inbox">
				<ul>
					<li {% if active_menu == "inbox" %}class="isactive"{% endif %}><a href="{% url 'messages_inbox' %}">{% trans "Inbox" %}</a></li>
					<li {% if active_menu == "outbox" %}class="isactive"{% endif %}><a href="{% url 'messages_outbox' %}">{% trans "Sent" %}</a></li>
					<li {% if active_menu == "create" %}class="isactive"{% endif %}><a href="{% url 'messages_compose' %}">{% trans "Send new message" %}</a></li>
				</ul>
			</div>
		</div>

	</div>

shortbus/templates/django_messages/outbox.html
{% extends 'django_messages/base_pm.html' %}
{% load forum_extras %}
{% load i18n %}
{% block sub_content %}
 <div class="blockform">
	<h2><span>{% trans "Outbox" %}</span></h2>
	<div class="box">
		<div class="inbox">
			<table cellspacing="0">
			<thead>
				<tr>
					<th class="tcl">{% trans "Subject" %}</th>
					<th>{% trans "Receiver" %}</th>
					<th class="tcr">{% trans "Date" %}</th>
				</tr>
			</thead>
			<tbody>
			{% if message_list %}
				{% for msg in message_list %}
				<tr>
					<td class="tcl">
						<div class="intd">
							<div class="icon"><div class="nosize"><!-- --></div></div>
							<div class="tclcon">
								<a href="{% url 'messages_detail' msg.id %}">{{ msg.subject }}</a>
							</div>
						</div>
					</td>
					<td class="tc2" style="white-space: nowrap; OVERFLOW: hidden"><a href="{% url 'djangobb:forum_profile' msg.recipient %}">{{ msg.recipient }}</a></td>
					<td class="tcr" style="white-space: nowrap">{% forum_time msg.sent_at %}</td>
				</tr>
				{% endfor %}
			{% else %}
				<tr><td class="djangobbcon1" colspan="3">{% trans "No messages" %}</td></tr>
			{% endif %}
			</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}

shortbus/templates/django_messages/view.html
{% extends 'django_messages/base_pm.html' %}
{% load forum_extras %}
{% load i18n %}

{% block sub_content %}

<div id="p2" class="blockpost row_odd firstpost" style="margin-left: 14em;">
		<h2><span>{% forum_time message.sent_at %}</span></h2>
		<div class="box">
			<div class="inbox">
				<div class="postleft">
					<dl>
						<dt><strong>{{ message.sender|profile_link }}</strong></dt>
						<dd>
						{% if message.sender.forum_profile.status %}
							<strong>{{ message.sender.forum_profile.status }}</strong>
						{% else %}
							<strong>{{ message.sender.forum_profile.group }}</strong>
						{% endif %}
						</dd>
						{% if forum_settings.AUTHORITY_SUPPORT %}
							<dd class="usertitle">
							{{ message.sender|forum_authority }}
							</dd>
						{% endif %}
						{% if message.sender.forum_profile.avatar and message.sender.forum_profile.show_avatar %}
							<dd class="postavatar"><img src="{{ message.sender.forum_profile.avatar.url }}" /></dd>
						{% else %}
							<dd class="postavatar"><img src="{% gravatar message.sender.email %}" /></dd>
						{% endif %}
						<dd>{% trans "Registered:" %} {{ message.sender.date_joined|date:"Y-m-d" }}</dd>
						<dd>{% trans "Posts:" %} {{ message.sender.posts.count }}</dd>
						{% if moderator %}
							<dd>{% trans "IP:" %} {{ post_user_ip }}</dd>
						{% endif %}
						<dd class="usercontacts"><a href="{% url 'djangobb:forum_profile' message.sender %}">{% trans "Profile" %}</a>&nbsp;&nbsp;
						{% if message.sender.forum_profile.privacy_permission == 0 %}
							<a href="mailto:{{ message.sender.email }}">{% trans "E-mail" %}</a>&nbsp;&nbsp;
						{% else %}
							{% if message.sender.forum_profile.privacy_permission == 1 %}
									<a href="{% url 'djangobb:misc' %}?mail_to={{ message.sender }}">{% trans "Send e-mail" %}</a>&nbsp;&nbsp;
							{% endif %}
						{% endif %}
						{% if user_is_authenticated %}
							<a href="{% url 'messages_reply' %}?recipient={{ post_user.username }}">{% trans "PM" %}</a>&nbsp;&nbsp;</dd>
						{% endif %}
					</dl>
				</div>
				<div class="postright">
					<div class="postmsg">
						{{ message.body|linebreaksbr }}
						{% if not user.is_authenticated or user.forum_profile.show_signatures %}
                    	{% if message.sender.forum_profile.signature %}
                    	<div class="postsignature">
                    		<br>
                    		---
							<br>
                    		{{ message.sender.forum_profile.signature|safe }}
                    	</div>
                    {% endif %}
                    {% endif %}
					</div>
					</div>
				<div class="clearer"></div>
				<div class="postfootleft">
				{% if message.sender|online %}
					<p><strong>{% trans "Online" %}</strong></p>
				{% else %}
					<p>{% trans "Offline" %}</p>
				{% endif %}
				</div>
				<div class="postfootright">
					<ul>
						<li>
							<a onclick="return confirm('{% trans "Are you sure you want to delete this post?" %}')" href="{% url 'messages_delete' message.id %}">{% trans "Delete" %}</a>
						</li>
						<li>
							| <a href="{% url 'messages_reply' message.id %}">{% trans "Reply" %}</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

shortbus/templates/djangobb_forum/base.html
{% load forum_extras %}
{% load i18n %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<title>{{ forum_settings.FORUM_BASE_TITLE }} {% block title %}{% endblock %}</title>
	<meta name="description" content="{{ forum_settings.FORUM_META_DESCRIPTION }} " />
	<meta name="keywords" content="{{ forum_settings.FORUM_META_KEYWORDS }}" />
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	
	{% set_theme_style request.user %}

	<link rel="alternate" type="application/atom+xml" href="{% url 'djangobb:forum_posts_feed' %}" title="{% trans "Latest posts on forum" %}" />
	<link rel="alternate" type="application/atom+xml" href="{% url 'djangobb:forum_topics_feed' %}" title="{% trans "Latest topics on forum" %}" />

	<link rel="shortcut icon" href="{{ STATIC_URL }}djangobb_forum/favicon.png" type="image/png" />
	<script type="text/javascript">
		var STATIC_URL = "{{ STATIC_URL }}";
		var POST_PREVIEW_URL = "{% url 'djangobb:post_preview' %}";
	</script>
	{% if DEBUG %}
	   <script type="text/javascript" src="{{ STATIC_URL }}admin/js/jquery.js" onerror="JavaScript:alert('Error loading file [' + this.src + '] !');" ></script>
	{% else %}
    	<script type="text/javascript" src="{{ STATIC_URL }}admin/js/jquery.min.js" onerror="JavaScript:alert('Error loading file [' + this.src + '] !');" ></script>
	{% endif %}
	{% if user.is_authenticated %}
    	{% if post %}
            {% with markup=post.markup %}
                {% include "djangobb_forum/includes/markup_editor.html" %}
            {% endwith %}
        {% else %}
            {% with markup=user.forum_profile.markup %}
                {% include "djangobb_forum/includes/markup_editor.html" %}
            {% endwith %}
        {% endif %}
    	<script type="text/javascript">
    	   $(document).ready(function() {
    		$(".markup").markItUp(mySettings);
    	   });
    	</script>
	{% endif %}

    <!-- Highlightjs goodies -->
	<link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}djangobb_forum/css/pygments.css" />
	{% if highlight_word %}
		<script type="text/javascript" src="{{ STATIC_URL }}djangobb_forum/js/jquery.highlight-3.pack.js"></script>
		<script type="text/javascript">
			$(document).ready(function(){
				$("div.postmsg").highlight("{{ highlight_word }}");
			});
		</script>
	{% endif %}
	{% block extra_meta %}{% endblock %}
</head>
<body>
    {% include 'djangobb_forum/subheader.html' %}

    {% block messages %}
        {% if messages %}
        <div id="messages" class="block">
            <h2><span>{% trans "Notice" %}</span></h2>
            <div class="box">
                <div class="inbox">
                    <ul class="messagelist">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        {% endif %}
    {% endblock messages %}

	{% block content %}{% endblock %}
	<div id="brdfooter" class="block">
	<h2><span>{% trans "Board footer" %}</span></h2>
        <div class="box">
            <div class="inbox">
                {% block controls %}
                    <dl id="searchlinks" class="conl">
                        <dt><strong>{% trans "Search links" %}</strong></dt>
                        <dd><a href="{% url 'djangobb:search' %}?action=show_24h">{% trans "Show recent posts" %}</a></dd>
                        <dd><a href="{% url 'djangobb:search' %}?action=show_unanswered">{% trans "Show unanswered posts" %}</a></dd>
                        {% if user.is_authenticated %}
                        <dd><a href="{% url 'djangobb:search' %}?action=show_subscriptions">{% trans "Show your subscribed topics" %}</a></dd>
                        <dd>{% trans "Show your" %} <a href="{% url 'djangobb:search' %}?action=show_user&show_as=topics">{% trans "topics" %}</a>/<a href="{% url 'djangobb:search' %}?action=show_user&show_as=posts">{% trans "posts" %}</a></dd>
                        {% endif %}
                    </dl>
                {% endblock controls %}
                <p class="conr">
                	{% if user.is_authenticated %}
			        <ul class="conr">
				        <li><a href="{% url 'djangobb:search' %}?action=show_new">{% trans "Show new posts since last visit" %}</a></li>
				        <li><a href="{% url 'djangobb:misc' %}?action=markread">{% trans "Mark all topics as read" %}</a></li>
			        </ul>
			        {% endif %}
                </p>
                <div class="clearer"></div>
                {% block lofi %}
                {% endblock lofi%}
            </div>
        </div>
    </div>
</div>
</div>
</body>
</html>

shortbus/templates/djangobb_forum/footer.html
hai!

shortbus/templates/djangobb_forum/index.html
{% extends 'djangobb_forum/base.html' %}
{% load forum_extras %}
{% load i18n %}

{% block extra_meta %}
<script type="text/javascript" src="{{ STATIC_URL }}djangobb_forum/js/jquery.cookie.js"></script>
<script type="text/javascript">

	function set_collapser(cat_id) {
		category_body_id = "category_body_" + cat_id;
		if($.cookie(category_body_id)){
			item_id = "#" + category_body_id;
			head_id = item_id.replace("body", "head");
			$(head_id).addClass("collapsed");
			$(item_id).hide()
		}
	}
	$(document).ready(function(){
		$("a.toggle").click(function(){
			header_id = $(this).parent().attr('id');
			body_id = header_id.replace("head", "body");
			item_id = '#' + body_id
			if ($(this).parent().attr('class')==''){
				$(this).parent().addClass("collapsed");
				$.cookie(body_id, 'collapsed');
			}else {
				$(this).parent().removeClass("collapsed");
				$.cookie(body_id, '');
			}
			$(item_id).slideToggle("slow");
		});
	{% for iter in cats %}
		set_collapser({{ iter.id }})
	{% endfor %}
	});
</script>
{% endblock %}

{% block content %}
<div id="idx1" class="blocktable">
{% for iter in cats %}
	<h2 id="category_head_{{ iter.id }}">
		<a class="toggle" href="#">Toggle shoutbox</a>
		<span>
			{{ iter.cat }}
		</span>
	</h2>
	<div class="box" id="category_body_{{ iter.id }}">
		<div class="inbox">
			<table cellspacing="0">
				<thead>
					<tr>
						<th class="tcl" scope="col">{% trans "Forum" %}</th>
						<th class="tc2" scope="col">{% trans "Topics" %}</th>
						<th class="tc3" scope="col">{% trans "Posts" %}</th>
						<th class="tcr" scope="col">{% trans "Last post" %}</th>
					</tr>
				</thead>
				<tbody>
				{% for forum in iter.forums %}
					{% include 'djangobb_forum/forum_row.html' %}
				{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
{% endfor %}
</div>

<div id="brdstats" class="block">
	<h2><span>{% trans "Board information" %}</span></h2>
	<div class="box">
		<div class="inbox">
			<dl class="conr">
				<dt><strong>{% trans "Board statistics" %}</strong></dt>
				<dd>{% trans "Total number of registered users:" %} <strong>{{ users }}</strong></dd>
				<dd>{% trans "Total number of topics:" %} <strong>{{ topics }}</strong></dd>
				<dd>{% trans "Total number of posts:" %} <strong>{{ posts }}</strong></dd>
			</dl>
			<dl class="conl">
				<dt><strong>{% trans "User information" %}</strong></dt>
				<dd>{% trans "Newest registered user:" %} {{ last_user|profile_link }}</dd>
				<dd>{% trans "Registered users online:" %} <strong>{{ online_count }}</strong></dd>
				<dd>{% trans "Guests online:" %} <strong>{{ guest_count }}</strong></dd>
			</dl>
            {% if online_count %}
                <dl id="onlinelist" class= "clearb">
                    <dt><strong>{% trans "Online:" %} </strong></dt>
                    {% for online in users_online %}
                        <dd>{{ online|profile_link }}</dd>
                    {% endfor %}
                </dl>
            {% endif %}
		</div>
	</div>
</div>
{% endblock %}

{% block lofi %}
{% if forum_settings.LOFI_SUPPORT %}
    <p class="lofi">
        <a href="{% url 'djangobb:lofi_index' %}">Lo-Fi Version</a>
    </p>
{% endif %}
{% endblock %}

shortbus/templates/djangobb_forum/subheader.html
{% extends 'header.html' %}
{% load i18n %}

        {% block subheader %}
		<div id="brdmenu" class="inbox">
			<ul>
			{% block menu %}
				{% if user.is_authenticated %}
				<li id="navprofile"><a href="{% url 'djangobb:forum_profile' request.user %}">{% trans "Profile" %}</a></li>
				{% endif %}		
				<li id="navuserlist"><a href="{% url 'djangobb:forum_users' %}">{% trans "User list" %}</a></li>
				<li id="navsearch"><a href="{% url 'djangobb:search' %}">{% trans "Search" %}</a></li>				
			{% endblock %}
			</ul>
		</div>
		<div class="clearer"></div>
		{% endblock %}

shortbus/templates/field/base.html
{% load forum_extras %}
{% load i18n %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<title>{{ forum_settings.FORUM_BASE_TITLE }} {% block title %}{% endblock %}</title>
	<meta name="description" content="{{ forum_settings.FORUM_META_DESCRIPTION }} " />
	<meta name="keywords" content="{{ forum_settings.FORUM_META_KEYWORDS }}" />
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	
	{% set_theme_style request.user %}
	<link rel="shortcut icon" href="{{ STATIC_URL }}djangobb_forum/favicon.png" type="image/png" />

	{% block extra_meta %}{% endblock %}
</head>
<body>
    {% include 'header.html' %}

	{% block content %}{% endblock %}
	<div id="brdfooter" class="block">
	<h2><span>{% trans "Board footer" %}</span></h2>
        <div class="box">
            <div class="inbox">
                	Footer!asdf
                <div class="clearer"></div>
            </div>
        </div>
    </div>
</div>
</div>
</body>
</html>

shortbus/templates/field/index.html
{% extends 'field/base.html' %}
{% load forum_extras %}
{% load i18n %}

{% block content %}
<div id="idx1" class="blocktable">
The spacial field...
</div>
{% endblock %}

shortbus/templates/header.html
{% load forum_extras %}
{% load i18n %}
<div id="djangobbwrap">
<div id="djangobbindex" class="djangobb">
<div id="brdheader" class="block">
	<div class="box">
		<div id="brdtitle" class="inbox">
			<ul class="conr">
				{% if user.is_authenticated %}
					<li>{% trans "Logged in as" %} <strong>{{ user.username }}</strong></li>
					<li>{% trans "Last visit:" %} {% forum_time user.last_login %}</li>
				{% else %}					
				    <li>{% trans "You are not logged in." %}</li>
				{% endif %}
				{% if user.is_superuser and reports %}
					<li class="reportlink"><strong><a href="{% url 'admin:index' %}">{% trans "There are new reports" %} ({% new_reports %})</a></strong></li>
				{% endif %}
			</ul>
			<h1><span><a href="{% url 'djangobb:index' %}">{{ forum_settings.HEADER|safe }}</a></span>
			</h1>
			<p><span>{{ forum_settings.TAGLINE|safe }}</span></p>
		</div>
		<div id="brdmenu" class="inbox">
			<ul>
				<li id="navhome"><a href="{% url 'index' %}">{% trans "Home" %}</a></li>
				<li id="navforum"><a href="{% url 'djangobb:index' %}">{% trans "Forum" %}</a></li>
				{% if user.is_authenticated %}
					<li id="navfield"><a href="{% url 'field:index' %}">{% trans "Field" %}</a></li>
					{% if forum_settings.PM_SUPPORT %}
					<li id="navpm"><a href="{% url 'messages_inbox' %}">
					    {% trans "Mail" %}
					    {% if messages_inbox_count > 0 %}
					    ({{messages_inbox_count}})
					    {% endif %}
					    </a>
					</li>
					{% endif %}
					<li id="navlogout"><a href="{% url 'account_logout' %}?next={{ request.path }}">{% trans "Log out" %}</a></li>
			        {% if user.is_superuser %}
				    <li id="navadmin"><a href="{% url 'admin:index' %}">{% trans "Administration" %}</a></li>
			        {% endif %}					
				{% else %}
                    <li><a href="{% url 'account_login' %}">{% trans "Log in" %}</a></li>
					<li><a href="{% url 'account_signup' %}">{% trans "Sign up" %}</a></li>
				{% endif %}
			</ul>				
		</div>
        {% block subheader %}{% endblock %}
	</div>
</div>

{% if forum_settings.NOTICE %}
	<div id="announce" class="block">
		<h2><span>{% trans "Notice" %}</span></h2>
		<div class="box">
			<div class="inbox">
				<div>{{ forum_settings.NOTICE }}</div>
			</div>
		</div>
	</div>
{% endif %}        

shortbus/templates/home/about.html
{% extends 'home/base.html' %}
{% load forum_extras %}
{% load i18n %}

{% block content %}
<div id="idx1" class="blocktable">
About page!
</div>
{% endblock %}

{% block lofi %}
{% if forum_settings.LOFI_SUPPORT %}
    <p class="lofi">
        <a href="{% url 'djangobb:lofi_index' %}">Lo-Fi Version</a>
    </p>
{% endif %}
{% endblock %}

shortbus/templates/home/base.html
{% load forum_extras %}
{% load i18n %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<title>{{ forum_settings.FORUM_BASE_TITLE }} {% block title %}{% endblock %}</title>
	<meta name="description" content="{{ forum_settings.FORUM_META_DESCRIPTION }} " />
	<meta name="keywords" content="{{ forum_settings.FORUM_META_KEYWORDS }}" />
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	
	{% set_theme_style request.user %}
	<link rel="shortcut icon" href="{{ STATIC_URL }}djangobb_forum/favicon.png" type="image/png" />

	{% block extra_meta %}{% endblock %}
</head>
<body>
    {% include 'home/subheader.html' %}

	{% block content %}{% endblock %}
	<div id="brdfooter" class="block">
	<h2><span>{% trans "Board footer" %}</span></h2>
        <div class="box">
            <div class="inbox">
                	Footer!
                <div class="clearer"></div>
            </div>
        </div>
    </div>
</div>
</div>
</body>
</html>

shortbus/templates/home/index.html
{% extends 'home/base.html' %}
{% load forum_extras %}
{% load i18n %}

{% block content %}
<div id="idx1" class="blocktable">
The landing page...
</div>
{% endblock %}

shortbus/templates/home/subheader.html
{% extends 'header.html' %}
{% load i18n %}

        {% block subheader %}
		<div id="brdmenu" class="inbox">
			<ul>
			{% block menu %}
				<li id="navabout"><a href="{% url 'about' %}">{% trans "About" %}</a></li>				
			{% endblock %}
			</ul>
		</div>
		<div class="clearer"></div>
		{% endblock %}